---
title: "examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{examples}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# grimm et al 2017 ch 14

[Tutorial Link](https://quantdev.ssri.psu.edu/tutorials/growth-modeling-chapter-14-modeling-change-latent-variables-measured-continuous-indicators)

```{r setup}
library(minvariance)
library(tidyverse)
library(lavaan)
library(semPlot)
```


```{r data}
data_url <- "https://quantdev.ssri.psu.edu/sites/qdev/files/ECLS_Science.csv"
#read in the .csv file using the url() function
data_raw <- read_csv(file = url(data_url)) %>% 
  select("id", "s_g3", "r_g3", "m_g3", "s_g5", "r_g5", "m_g5", "s_g8", "r_g8", "m_g8")

# rename so functions work
data <- data_raw
names(data) <- c("id", "x_t1_i1", "x_t1_i2", "x_t1_i3", "x_t2_i1", "x_t2_i2", "x_t2_i3", "x_t3_i1", "x_t3_i2", "x_t3_i3")

data
```



```{r}
# test functions
specify_latent_factors(n_items = 3, n_timepoints = 3, model = "strict") %>% cat()
specify_latent_variable_variances(n_items = 3, n_timepoints = 3, model = "strict") %>% cat()
specify_unique_variances(n_items = 3, n_timepoints = 3, model = "strict") %>% cat()
specify_latent_variable_means(n_items = 3, n_timepoints = 3, model = "strict") %>% cat()
specify_observed_intercepts(n_items = 3, n_timepoints = 3, model = "strict") %>% cat()
```


```{r}
# specify covariances, my functions dont really work for this atm
latent_variable_covariances <- c(
"# Latent Variable Covariances ----
eta1 ~~ eta2
eta1 ~~ eta3
eta2 ~~ eta3")

unique_covariances <- c(
"\n# Unique Covariances ----
x_t1_i1 ~~ x_t2_i1
x_t1_i1 ~~ x_t3_i1
x_t2_i1 ~~ x_t3_i1
x_t1_i2 ~~ x_t2_i2
x_t1_i2 ~~ x_t3_i2
x_t2_i2 ~~ x_t3_i2
x_t1_i3 ~~ x_t2_i3
x_t1_i3 ~~ x_t3_i3
x_t2_i3 ~~ x_t3_i3")
```


```{r}
# long_minvariance_syntax(n_items = 3, n_timepoints = 3, model = "configural", add = c(latent_variable_covariances, unique_covariances)) %>% cat()
configural <- long_minvariance_syntax(n_items = 3, n_timepoints = 3, model = "configural", add = c(latent_variable_covariances, unique_covariances))

# configural %>% cat

fit_configural <- lavaan(configural,
                         data = data,
                         meanstructure = TRUE,
                         estimator = "ML",
                         missing = "fiml",
                         fixed.x = FALSE)

summary(fit_configural, fit.measures=TRUE)
```


```{r fig.height=5, fig.width=5, dpi=100}

semPaths(fit_configural, 
         what="path",
         whatLabels = "name",
         sizeInt = 4, sizeMan = 5, sizeLat = 6
         )

```


```{r}
# long_minvariance_syntax(n_items = 3, n_timepoints = 3, model = "strict", add = c(latent_variable_covariances, unique_covariances)) %>% cat()
strict <- long_minvariance_syntax(n_items = 3, n_timepoints = 3, model = "strict", add = c(latent_variable_covariances, unique_covariances))


fit_strict <- lavaan(strict,
                         data = data,
                         meanstructure = TRUE,
                         estimator = "ML",
                         missing = "fiml",
                         fixed.x = FALSE)

summary(fit_strict, fit.measures=TRUE)
```


```{r fig.height=5, fig.width=5, dpi=100}

semPaths(fit_strict, 
         what="path",
         whatLabels = "name",
         sizeInt = 4, sizeMan = 5, sizeLat = 6
         )

```

```{r}

long_minvariance(data = data, n_items = 3, n_timepoints = 3, add = c(latent_variable_covariances, unique_covariances)) %>% 
  knitr::kable(digits = 3)

```

# intro ram long factor analysis measurement invariance

[Tutorial Link](https://quantdev.ssri.psu.edu/tutorials/intro-basics-longitudinal-measurement-invariance)

```{r}
#set filepath for data file
filepath <- "https://quantdev.ssri.psu.edu/sites/qdev/files/WISC_MIexample.csv"
#read in the .csv file using the url() function
dat <- read_csv(file = url(filepath))


names(dat) <- c("id", "x_t1_i1", "x_t1_i2", "x_t1_i3", "x_t1_i4", "x_t2_i1", "x_t2_i2", "x_t2_i3", "x_t2_i4")
```


```{r}
# specify covariances, my functions dont really work for this atm
latent_variable_covariances <- c(
"# Latent Variable Covariances ----
eta1 ~~ eta2")

unique_covariances <- c(
"\n# Unique Covariances ----
x_t1_i1 ~~ x_t2_i1
x_t1_i2 ~~ x_t2_i2
x_t1_i3 ~~ x_t2_i3
x_t1_i4 ~~ x_t2_i4")
```




```{r}
configural_t2_i4 <- long_minvariance_syntax(n_items = 4, n_timepoints = 2, model = "configural"
                                      , add = c(latent_variable_covariances, unique_covariances)
                                      ) 


configural_t2_i4 %>% cat()

fit_configural <- lavaan(configural_t2_i4,
                         data = dat,
                         meanstructure = TRUE,
                         estimator = "ML",
                         missing = "fiml",
                         fixed.x = FALSE)

summary(fit_configural, fit.measures = TRUE)
```


```{r fig.height=5, fig.width=5, dpi=100}

semPaths(fit_configural, 
         what="path",
         whatLabels = "name",
         sizeInt = 4, sizeMan = 5, sizeLat = 6
         )

```



```{r}

long_minvariance(data = dat, n_items = 4, n_timepoints = 2, add = c(latent_variable_covariances)) %>% 
  knitr::kable(digits = 3)

```
