---
title: "Replicating Online Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Replicating Online Tutorial}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

- [Tutorial Link (by Nilam Ram)](https://quantdev.ssri.psu.edu/tutorials/intro-basics-longitudinal-measurement-invariance)


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(minvariance)
library(tidyverse)
library(lavaan)
library(semPlot)
```

## Load data

```{r}

filepath <- "https://quantdev.ssri.psu.edu/sites/qdev/files/WISC_MIexample.csv"
df <- read_csv(file = url(filepath))

```

## Remove correlated uniqueness

```{r}
# Correlated uniqueness can be removed using the "remove" argument
configural <- long_minvariance_syntax(var_list = list(t1 = c("info1", "comp1", "simi1", "voca1"),
                                                      t6 = c("info6", "comp6", "simi6", "voca6")),
                                      model = "configural", 
                                      remove = list(unique_covar = TRUE))

fit_configural <- cfa(configural,
                      data = df)


summary(fit_configural, fit.measures = TRUE)

```

```{r fig.height=5, fig.width=5, dpi=100}

semPaths(fit_configural, 
         what="path",
         whatLabels = "name",
         sizeInt = 4, sizeMan = 5, sizeLat = 6)

```

## Includeing correlated uniqueness

```{r}

configural_unique <- long_minvariance_syntax(var_list = list(t1 = c("info1", "comp1", "simi1", "voca1"),
                                                             t6 = c("info6", "comp6", "simi6", "voca6")),
                                             model = "configural")

fit_configural_unique <- cfa(configural_unique,
                             data = df)

summary(fit_configural_unique, 
        fit.measures = TRUE)

```

```{r fig.height=5, fig.width=5, dpi=100}

semPaths(fit_configural_unique, 
         what="path",
         whatLabels = "name",
         sizeInt = 4, sizeMan = 5, sizeLat = 6)

```

## Fit statistics

```{r}

minvariance(data = df, 
            var_list = list(t1 = c("info1", "comp1", "simi1", "voca1"),
                            t6 = c("info6", "comp6", "simi6", "voca6")),
            remove = list(unique_covar = T), 
            return = "fit_statistics") %>% 
  knitr::kable(digits = 3)

```

## Model tests

```{r}

minvariance(data = df, 
            var_list = list(t1 = c("info1", "comp1", "simi1", "voca1"),
                            t6 = c("info6", "comp6", "simi6", "voca6")),
            remove = list(unique_covar = T), 
            return = "model_tests") %>% 
  knitr::kable(digits = 3)

```


## lavaan syntax


```{r}

lminvar_syntax <- minvariance(data = df, 
                              var_list = list(t1 = c("info1", "comp1", "simi1", "voca1"),
                                              t6 = c("info6", "comp6", "simi6", "voca6")),
                              remove = list(unique_covar = T), 
                              return = "lavaan_syntax") 

```

### Configural

```{r}

lminvar_syntax$configural %>% 
  cat()

```


### Weak

```{r}

lminvar_syntax$weak %>% 
  cat()

```


### Strong

```{r}

lminvar_syntax$strong %>% 
  cat()

```


### Strict

```{r}

lminvar_syntax$strict %>% 
  cat()

```
